提交代码
imc-ux/ReportsMS pull request #11
Opened 2023-12-26 02:11 UTC by liujinhai8410

### 这个变动的性质是？
- [ ] New feature
- [ ] Bug fix
- [ ] Refactoring
- [x] Branch merge
- [ ] Other (about what?)
### 相关 Issue
1. 消息管理页面代码提交

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 代码格式化已进行
- [x] 代码开发基准核对完成
- [x] 样式设计已确认或无样式变动
 
### 概述
消息管理页面代码提交合并

2023-12-26 05:12 UTC, ythyhvh requested changes
把行内样式都转移到Class里

2023-12-26 05:18 UTC, ythyhvh requested changes
components/TemplateComponent.vue     这个文件命名不合适， 和康家旗一起修改

2023-12-27 02:10 UTC, liujinhai8410 commented
pr已提交

2023-12-27 02:13 UTC, liujinhai8410 commented
pr已提交

2023-12-28 00:42 UTC, ythyhvh approved these changes
done

2023-12-28 00:42 UTC, merged