issue
imc-ux/ReportsMS pull request #35
Opened 2024-01-02 09:15 UTC by liujinhai8410

### 这个变动的性质是？
- [ ] New feature
- [x] Bug fix
- [ ] Refactoring
- [ ] Branch merge
- [ ] Other (about what?)
### 相关 Issue
1. fix #33 #32 #24 #22 #17 

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 代码格式化已进行
- [x] 代码开发基准核对完成
- [x] 样式设计已确认或无样式变动
 
### 概述
1. fix #33 #32 #24 #22 #17

2024-01-03 01:31 UTC, ythyhvh commented
@liujinhai8410  PR格式里的  相关 Issue 概述 需要调整

2024-01-03 01:37 UTC, liujinhai8410 commented
已修改，请确认

2024-01-03 01:42 UTC, ythyhvh requested changes
修改以上

2024-01-03 01:42 UTC, ythyhvh commented on components/MarkDownTable.vue
> +            for (let z = 0; z < contentArr.length; z++) {
都用 forEach

2024-01-03 01:42 UTC, ythyhvh commented on pages/messageMain/index.vue
> +function getDateFormat(date: any) {
类型不写any

2024-01-03 01:42 UTC, ythyhvh commented on pages/messageMain/index.vue
> +function getDateFormat(date: any) {
用正规的日期格式转换   不要手写

2024-01-03 05:59 UTC, liujinhai8410 commented
问题已修改

2024-01-03 06:09 UTC, ythyhvh approved these changes
done

2024-01-03 06:10 UTC, merged

2024-01-18 06:00 UTC, liujinhai8410 commented
遗漏fix #21 问题，已提交